version: '3'
services:
  server:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mariadb:10.2.12
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - "./.db-data:/var/lib/mysql"
    ports:
      - "${DB_PORT:-3306}:3306"
