version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0

executors:
  docker_build:
    # machine:
    #   docker_layer_caching: true

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          executor: docker_build
          name: 'build-production'
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          region: AWS_DEFAULT_REGION
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master
      - aws-ecs/deploy-service-update:
          requires:
            - build-production
          aws-region: ${AWS_DEFAULT_REGION}
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master