version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0

jobs:
  set-master-key:
    docker:
      - image: circleci/python:3.4
    steps:
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls -la
          command: ls -la
      - run:
          name: create master.key
          command: echo "${RAILS_MASTER_KEY}" > ~/app/config/master.key


workflows:
  build-and-deploy:
    jobs:
      - set-master-key
      - aws-ecr/build-and-push-image:
          requires:
            - set-master-key
          name: 'build-production'
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          region: AWS_DEFAULT_REGION
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master
      - aws-ecs/deploy-service-update:
          requires:
            - build-production
          aws-region: ${AWS_DEFAULT_REGION}
          family: "react-rails-ecs-task-definition-family"
          cluster-name: "react-rails-ecs-cluster"
          service-name: "react-rails-ecs-service-web"
          container-image-name-updates: "container=web, image-and-tag=${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master