version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0

references:
  filters:
    staging_branch_filter: &staging_branch_filter
      filters:
        branches:
          only:
            - staging
    master_branch_filter: &master_branch_filter
      filters:
        branches:
          only:
            - master

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          name: 'staging_build'
          account-url: todo
          region: AWS_DEFAULT_REGION
          repo: todo
          tag: "${CIRCLE_SHA1}"
          <<: *staging_branch_filter
      - aws-ecs/deploy-service-update:
          requires:
            - staging_build
          name: 'staging_deploy'
          aws-region: ${AWS_DEFAULT_REGION}
          family: todo
          cluster-name: todo
          service-name: todo
          container-image-name-updates: todo
          <<: *staging_branch_filter

      - aws-ecr/build-and-push-image:
          name: 'production_build'
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          region: AWS_DEFAULT_REGION
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          <<: *master_branch_filter
      - aws-ecs/deploy-service-update:
          requires:
            - production_build
          name: 'production_deploy'
          aws-region: ${AWS_DEFAULT_REGION}
          family: "react-rails-ecs-task-definition-family"
          cluster-name: "ecs-cluster"
          service-name: "react-rails-ecs-service-web"
          container-image-name-updates: "container=web, image-and-tag=${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"
          <<: *master_branch_filter