version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@1.1.0

# executors:
#   docker_build:
#     machine:
#       docker_layer_caching: true

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          name: 'build-production'
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          region: AWS_DEFAULT_REGION
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master
      - aws-ecs/deploy-service-update:
          requires:
            - build-production
          aws-region: ${AWS_DEFAULT_REGION}
          family: "react-rails-ecs-task-definition-family"
          cluster-name: "react-rails-ecs-cluster"
          container-image-name-updates: "container=web, image-and-tag=${AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME}/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - master